# Generated by Django 3.2.7 on 2021-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('benz_price', models.FloatField()),
                ('cost', models.FloatField()),
                ('mileage', models.FloatField()),
                ('mileage_total', models.FloatField()),
                ('consump', models.FloatField()),
                ('saving', models.FloatField()),
            ],
        ),
    ]
