# Generated by Django 3.2.7 on 2021-12-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='STO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('action', models.ManyToManyField(to='sto.Action')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stos', to='sto.group')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
