# Generated by Django 3.2.7 on 2021-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
