# Generated by Django 3.2.7 on 2021-12-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0002_auto_20211224_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sto',
            old_name='action',
            new_name='actions',
        ),
    ]
