# Generated by Django 3.2.7 on 2021-12-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0003_rename_action_sto_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sto',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sto',
            name='date',
            field=models.DateField(),
        ),
    ]
