# Generated by Django 3.2.7 on 2021-12-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0004_auto_20211227_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
    ]
