# Generated by Django 3.2.7 on 2021-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(help_text='Введите текст задачи', max_length=300, verbose_name='Текст задачи'),
        ),
    ]
